version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - langserve
    environment:
      LANGSERVE_URL: "http://langserve:8000/langserve"  # 確保 FastAPI 連到 LangServe
    networks:
      - mynet

  langserve:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
